### ISSUE TITLE
The string "a = nan" breaks the page

### ISSUE THREAD

**Issue by PetterS** [bobfang1992/toml-online-parser#4]
The following input breaks the page:
```
a = nan
```

**Comment by bobfang1992** [comment]
I think toml does not support "nan" as a value. I am not following the spec change closely enough, do you think this should work? 
cc. @marzer

**Comment by marzer** [comment]
Yup, `nan` is valid in toml, as is `inf`, and both can have a leading `+` or `-`

**Comment by marzer** [comment]
```toml
a = nan
b = inf
c = +nan
d = -nan
e = +inf
f = -inf
```

should all be valid
